# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Setup Python environment
        uses: actions/setup-python@v2.2.2
        with:
            python-version: 2.7
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Install Python Modules
        run: |
         pip install requests

      - name: Download ResHack
        shell: python        
        run: |
         import requests
         import shutil
         file_url = 'http://www.angusj.com/resourcehacker/resource_hacker.zip'
         res = requests.get(url=file_url)
         with open(r'Store.zip',mode='wb') as f:
             f.write(res.content)
         import zipfile  
         def un_zip(file_name):  
             """unzip zip file"""  
             zip_file = zipfile.ZipFile(file_name)  
             for names in zip_file.namelist():  
                 zip_file.extract(names)
             zip_file.close()
         un_zip("Store.zip")

      - name: Install Build deps
        run: |
         Set-ExecutionPolicy Unrestricted -Force
         iex ((New-Object System.Net.WebClient).DownloadString('https://boxstarter.org/bootstrapper.ps1'))
         get-boxstarter -Force
         Install-BoxstarterPackage https://raw.githubusercontent.com/nodejs/node/master/tools/bootstrap/windows_boxstarter -DisableReboots

      - name: Build
        run: |
         node bootstrap.js hexa.json
         npm i -g nexe
         .\nexe-build.bat
         mkdir dist
         copy hexa-node.js dist
         copy hexa.exe dist

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Hexa
          path: './dist/*'
