# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.1

      - name: Setup Python environment
        uses: actions/setup-python@v2.2.2
        with:
            python-version: 2.7

      - name: Install Python Deps
        shell: powershell
        run: |
         pip install requests

      - name: Download NodeJS
        shell: python        
        run: |
         import requests
         file_url = 'https://nodejs.org/dist/v16.13.0/node-v16.13.0-win-x64.zip'
         res = requests.get(url=file_url)
         with open(r'Store.zip',mode='wb') as f:
             f.write(res.content)
         import zipfile  
         def un_zip(file_name):  
             """unzip zip file"""  
             zip_file = zipfile.ZipFile(file_name)  
             for names in zip_file.namelist():  
                 zip_file.extract(names)
             zip_file.close()
         un_zip("Store.zip")

      - name: Build
        shell: powershell
        run: |
         dir
         node bootstrap.js hexa.json
         mkdir dist
         copy hexa-node.js dist
         copy hexa.cmd dist
         copy node-v16.13.0-win-x64\node.exe dist

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Hexa
          path: './dist/*'

      - name: Package Release
        shell: python
        if: startsWith(github.ref, 'refs/tags/')
        run: |
         import zipfile
         def zip_files( files, zip_name ):
             zip = zipfile.ZipFile( zip_name, 'w', zipfile.ZIP_DEFLATED )
             for file in files:
                 zip.write(file)
             zip.close()
         files = ['.\\dist\\hexa-node.js', '.\\dist\\hexa.cmd', '.\\dist\\node.exe']
         zip_file = '.\\hexa-${{ github.ref }}.zip'
         zip_files(files, zip_file)

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          file_glob: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: hexa-${{ github.ref }}.zip
          tag: ${{ github.ref }}
          overwrite: true
